### ISSUE TITLE
Testing floats no longer works

### ISSUE THREAD

**Issue by talex5** [mirage/alcotest#106]
In addition to the API changing in 0.8.0, it seems it is no longer possible to compare two floats exactly. Maybe have separate `float` and `float_approx`, or use `<=` rather than `<`?

**Comment by samoht** [comment]
Equality between floats is not properly defined, so I think it was a good idea to break the API (so that people could fix their code :-))

**Comment by talex5** [comment]
Are you sure? I thought most floating point operations were specified exactly, down to the bit pattern they should produce. It seems strange that I can only check I calculate approximately the right answer, when I know the exact answer I should get.

**Comment by samoht** [comment]
> or use <= rather than <

I guess it's to be able to use `Alcotest.float 0.`? What do you think @superbobry and @ryanrhymes (who initially made the PR?)

**Comment by superbobry** [comment]
There're indeed case when you might want to check for exact (bitwise) equality. I think it's a good idea to refine the float comparison API and consider including absolute/relative difference & ULP-based variants.

**Comment by ryanrhymes** [comment]
I agree with @superbobry , the refined API looks reasonable to me. Having separate `float` and `float_approx` also seems good regarding compatibility and easy to understand :)

**Comment by samoht** [comment]
The API is already broken, and as I said, I think it was a good idea: the default `float` combinator should be one taking an epsilon. If you both agree I will just change `<` to `<=` so one can use `float 0.` to have an "exact" comparison.

**Comment by ryanrhymes** [comment]
@samoht Sure I agree,  changing to `<=` is the best solution atm imo
