### ISSUE TITLE
Test output missing line numbers in case of error

### ISSUE THREAD

**Issue by marco-m** [mirage/alcotest#112]
Hello,
I am learning OCaml and I am used to TDD, for me fast navigation from test output to failing test is of utmost importance. I took the simple example from the README and modified to make it fail:

```
let capit () =
  Alcotest.(check char) "same chars"  'X' (To_test.capit 'a')

let capit2 () =
  Alcotest.(check char) "same chars"  'X' (To_test.capit 'a')

let test_set = [
  "Capitalize" , `Quick, capit;
  "Capitalize" , `Quick, capit2;
  "Add entries", `Slow , plus ;
]
```

Here I duplicated on purpose `capit` and `capit2` to better show the usability problem I see.

The test output is:
```
./test_simple.native
Testing My first test.
[ERROR]             test_set          0   Capitalize.
[ERROR]             test_set          1   Capitalize.
[OK]                test_set          2   Add entries.
The full test results are available in `_build/_tests`.
2 errors! in 0.000s. 3 tests run.
```

How am I supposed to find the failing test? By searching for the test description string "Capitalize", hoping that the string is unique?

Also if I run with the `-e` flag, I get:
```
./test_simple.native -e
Testing My first test.
[ERROR]             test_set          0   Capitalize.
[ERROR]             test_set          1   Capitalize.
[OK]                test_set          2   Add entries.
-- test_set.000 [Capitalize.] Failed --
in _build/_tests/test_set.000.output:
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
ASSERT same chars
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[failure] Error same chars: expecting
X, got
A.

-- test_set.001 [Capitalize.] Failed --
in _build/_tests/test_set.001.output:
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
ASSERT same chars
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[failure] Error same chars: expecting
X, got
A.

The full test results are available in `_build/_tests`.
2 errors! in 0.001s. 3 tests run.
```

Here I have the same problem: Maximum I can do is to search for the string "same chars" and hope it is unique.

To make a comparison with, for example, the google test C++ Unit Test library:

- Test failure as always the line number, so that it is very easy to integrate Editor or IDE navigation to the failing test.
- There is no need for the test registration (what is done in Alcotest with the `test_set`. In general test registration is not only useless boilerplate, it is also error prone because you can forget to register a test you wrote.
- There is no need for a textual description of the test, it is the function name that is used as test name in the output. This not only allows for better DRY, it also allows the compiler to catch duplicated names.

Or am I missing something?

**Comment by samoht** [comment]
Short answer: the test description ("same char") is indeed supposed to be unique. If you want the compiler to generate a unique string for you, which will include the file and line number, you can use the symbol [`__LOC__`](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Pervasives.html#VAL__LOC__).

**Comment by samoht** [comment]
> There is no need for the test registration (what is done in Alcotest with the test_set. In general test registration is not only useless boilerplate, it is also error prone because you can forget to register a test you wrote.

That design (test registration) is done on purpose: this is pretty useful when you have a library of tests, that you want to instrument for various backends. If you forget to register your test, the compiler will tell you that the symbol is not used (if you use jbuilder, use `jbuilder runtest --dev` to enable warnings as errors).

**Comment by marco-m** [comment]
Closing since it seems you don't consider this a bug.
