### ISSUE TITLE
Why is the examples/bad.ml bad?

### ISSUE THREAD

**Issue by bobbypriambodo** [mirage/alcotest#113]
[examples/bad.ml](https://github.com/mirage/alcotest/blob/master/examples/bad.ml)

I think it could use some explanation of contexts as I don't think it's clear on first glance.

**Comment by samoht** [comment]
It's bad because it fails (and so cannot be run automatically) :-) 

I am using it to test the output of alcotest when there are failures.

**Comment by bobbypriambodo** [comment]
Aah okay, thanks for answering, @samoht 🙂
