### ISSUE TITLE
Test case names are used directly for filesystem interactions

### ISSUE THREAD

**Issue by cfcs** [mirage/alcotest#115]
Hello! I'm taking Alcotest for a spin, and my very first test case happened to be en-/decoding of values.

So I wrote up:
```ocaml
let test_int () =
  Alcotest.(check int) "same int" 1234 (1234)

let tests =
  [
    "integer en/decoding",
      ["check that ints are good", `Slow, test_int ];
  ]

let () =
  Alcotest.run "my test suite" tests
```

and it gave me this error:
```
$ topkg te
Testing my test suite.
 ...                integer en/decoding          0   check that ints are good.alcotest_lib.native: internal error, uncaught exception:
                     Unix.Unix_error(Unix.ENOENT, "open", "_build/_tests/integer en/decoding.000.output")
                     
pkg.ml: [ERROR] Some tests failed.
```

This turned out to be caused by the slash in the test case name. Changing it to `integer en- and decoding` made it work. It was a little bit counter-intuitive to me as a new user of the library, but I guess it's a corner case - wanted to let you know either way. I like all the colors! :-)

**Comment by CraigFe** [comment]
Thanks! This has been fixed by a whitelist of characters in test names, and a line added in the README, so hopefully this will be less counter-intuitive in future :slightly_smiling_face:
