### ISSUE TITLE
Making Alcotest more asynchronous

### ISSUE THREAD

**Issue by aantron** [mirage/alcotest#119]
`alcotest-lwt` currently [calls `Lwt_main.run`](https://github.com/mirage/alcotest/blob/ebe9cf2be006c626a6994dd4f684b8c6f722b141/lwt/alcotest_lwt.ml#L17-L29) for each test, in order to convert a Lwt test that is executed asynchronously into a synchronous one that completes before the function returns.

We would like to use `alcotest-lwt`, or similar modules, in Lwt and elsewhere, but `Lwt_main.run` is not available on Node.js or in browsers – there is no way to convert asynchronous code to synchronous by waiting on something.

We basically would need Alcotest to have fully-asynchronous tests, and to push `Lwt_main.run` to one place as far to the end of the test runner as possible. Ideally, `Alcotest.run` itself would return a promise.

Something similar had to be done to the Lwt tester recently, and it is what is preventing us from replacing it with Alcotest: https://github.com/ocsigen/lwt/commit/5a272758adbdf9bf21a874377605b224e0753851#diff-fa96e02582bba62b4c7d8bac70d3e8e7.

cc @kennetpostigo

**Comment by aantron** [comment]
One way to do this probably, without infecting `alcotest.mli` with monads, is to convert Alcotest to use continuation-passing style to chain its tests, and maybe provide an optional continuation argument to `Alcotest.run`. Then, people that don't care about asynchronous testing and aren't using `alcotest-lwt` shouldn't be affected, but users who care can use the continuation.

**Comment by aantron** [comment]
See this comment in Lwt about translating between CPS and Lwt promises: https://github.com/ocsigen/lwt/pull/206#issuecomment-265138123.

**Comment by samoht** [comment]
I indeed not too fond of contaminating the core library with `Lwt` :-)

However, since 0.8.0, `test_case` are now polymorphic in their inputs (e.g. the first argument passed to the testing function). We should check that it won't break anything, but I think we can do the same thing for outputs:

```
type ('a, 'b) test_case = string * speed_level * ('a -> 'b)
```

By default, `a` and `'b` will be `unit` but `Alcotest_lwt` could thread `Lwt.t` in there. WDYT?

PR are welcome; especially if they help integrating alcotest in lwt :-)

**Comment by aantron** [comment]
I'm not sure what the effect would be of changing this type. The important thing is that the overall Alcotest runner needs to become asynchronous, i.e. not assume that a test case will finish running when the test case function returns. Test cases should now be considered finished when a promise resolves, or when a callback call occurs, or when some equivalent asynchronous event happens.

I think this can be done even without changing the API, but API improvements are welcome, too :)

**Comment by brendanlong** [comment]
We're running into similar problems with Async, where alcotest-async calls `Thread_safe.block_on_async_exn` for each test, which can't be called inside the Async event loop. This means we can't do any async computation during our test setup, and have to move all code into the individual tests (which can introduce significant delays if we're trying to integration test server code). Being able to run Alcotest inside an existing event loop would be really helpful.

**Comment by brendanlong** [comment]
Ah I did figure out a workaround though, by running Alcotest in a background thread:

```
let () =
  Api_server.with_server (fun server ->
    In_thread.run @@ fun () ->
    [ long list of async tests ]
    |> Alcotest.run "api tests")
  |> don't_wait_for;
  Scheduler.go ()
  |> never_returns;
```

But this would still be less awkward if Alcotest integrated more easily with Async and Lwt.

**Comment by aantron** [comment]
Thanks @CraigFe and @samoht!
