### ISSUE TITLE
Missing comparison with other testing frameworks

### ISSUE THREAD

**Issue by vog** [mirage/alcotest#132]
It would be great if the README (or another good place in the documentation) could mention a short comparison to other common testing frameworks, such ounit. What are the advantages? What are the drawbacks? When to use alcotest, when to use ounit?

**Comment by samoht** [comment]
The README is pretty clear about that:

> Alcotest is a lightweight and colourful test framework.

Which says it all :-)

More seriously, it's a good idea but I am not sure Alcotest README is the best place to do it (but maybe it is).

As a quick answer, I would say that in a way, `Alcotest` is very similar to `ounit` as I used to use `ounit` a lot, but I was a bit frustrated by some aspects of it: basically a messy output and a lack of combinators for defining pretty-printer/equality between things to test.

If you want random generator and property testing, you should look at qcheck. If you want compiler-directed randomness, look at crowbar/bun.

If you want inline tests, you should look at ppx_inline_test and qtest.

**Comment by vog** [comment]
Thanks for this very useful overview over existing OCaml testing frameworks.

I still believe that this information should be put at a more visible place, rather than being hidden in this GitHub issue.
