### ISSUE TITLE
"Alcotest is the only testing framework using colors!" please show a screenshot?

### ISSUE THREAD

**Issue by Naereen** [mirage/alcotest#136]
Hi!

Your project seems mature and very nice, it's awesome to see tools like this in OCaml!

I only have a small remark, in the subtitle and the description of the project you advertise it by saying "Alcotest is the only testing framework using colors!", and yet we don't see colors in any examples presented in the description!
Including code for examples is nice, but it doesn't show the colors.
I would suggest to include (at least) a nice screenshot showing input/output of an example and the colors!

Regards :smiley:.

**Comment by rizo** [comment]
Sounds like a valid complaint! ;)

[odoc](https://github.com/ocaml/odoc/) uses alcotest, here are some screenshots of our tests:

#### All tests passed
<img width="828" alt="odoc-tests-passed" src="https://user-images.githubusercontent.com/308413/45678698-ef26fe80-bb2e-11e8-8e7e-1db0107a0c42.png">

#### Some tests failed
<img width="828" alt="odoc-tests-failed" src="https://user-images.githubusercontent.com/308413/45678699-ef26fe80-bb2e-11e8-9307-6478f23f2c7c.png">

#### Failed test diff
<img width="828" alt="odoc-tests-diff" src="https://user-images.githubusercontent.com/308413/45678700-ef26fe80-bb2e-11e8-8398-ee2252d0090c.png">

**Comment by Naereen** [comment]
That's nice! You could add them to the `README.md` document of alcotest.

**Comment by rizo** [comment]
Let’s see what the maintainers think about it first.

**Comment by samoht** [comment]
That's a very good idea, please add the pictures to the README :-)

**Comment by samoht** [comment]
ping :-)

**Comment by rizo** [comment]
[Done!](https://github.com/rizo/alcotest/tree/screenshots#screenshots) :-)

**Comment by samoht** [comment]
Thanks!
