### ISSUE TITLE
A more quiet output

### ISSUE THREAD

**Issue by emillon** [mirage/alcotest#146]
Hi,

When using alcotest, I noticed that it is very verbose when there are no failures. When there are many tests and they are run in a tight loop, it's not immediately obvious if there are failures or not.

Ideally, what I'm after is a mode where only failures are displayed (or something very simple like one dot per passing test case).

I'm happy to provide a PR to add a flag if this is something you agree with.

Thanks!

**Comment by samoht** [comment]
Having a "quiet" mode makes sense to me (for instance using `--mode quiet` or `--quiet` if that doesn't conflict with the current flags); 

I kind of like when I see lots of green checkboxes ("e.g. lots of things work great!") but I understand there are use-cases when you just wants to see nothing when everything is good.

**Comment by CraigFe** [comment]
Closing as #149 added a `--silent` flag.
