### ISSUE TITLE
First element of `argv` is ignored by `Alcotest.run`

### ISSUE THREAD

**Issue by ian-barnes** [mirage/alcotest#163]
If you try to pass a command-line option to `Alcotest.run` like this:
```
Alcotest.run ~argv:[| "--verbose" |] "Title" [ ("Suite", tests) ]
```
it has no effect. But add another string in the first position like this:
```
Alcotest.run ~argv:[| "ignored?"; "--verbose" |] "Title" [ ("Suite", tests) ]
```
and it works just fine.

From a quick look at the code, the array is getting passed unchanged to `Cmdliner.Term.eval_choice` on line 606 of `alcotest.ml`. That function has a default that sets `argv` to `Sys.argv`, so it makes sense that when looking for args, they ignore the first element, because in the default case it is the command name.

Options:

- Prepend something to the array passed to `Cmdliner.Term.eval_choice`; or

- Change the documentation for `Alcotest.run` to make it clear that the first element of `argv` will be ignored.

I didn't have time to check regression/history, but I'm guessing this is relatively recent, because there's no mention of it in #121, where @basus does this:
```
let argv = Array.of_list ["--verbose"] in
run s.title ~argv [("Suite", test_set)]
```

**Comment by emillon** [comment]
I believe that the intent (carried by the `~argv` name) is that it should be interpreted as `Sys.argv` would be, so fixing the docs seems better.

**Comment by ian-barnes** [comment]
Fair enough. I'm still baffled as to why @basus's code snippet that I quoted above worked (apparently).
