### ISSUE TITLE
Support unicode test names

### ISSUE THREAD

**Issue by CraigFe** [mirage/alcotest#171]
Currently, test names may contain only a small whitelist of characters (alphanumerics, `_`, `-`, ` `), due to test names being used directly as folder names. 

This restriction could be avoided by sanitizing the file-names as suggested [here](https://github.com/mirage/alcotest/pull/161#issuecomment-517623549).

**Comment by gs0510** [comment]
Hi! I'm looking to pick up this issue. One of the concerns with https://github.com/mirage/alcotest/pull/161#issuecomment-517623549 was `-` might be wonky if someone uses the same test name except for different emojis. What about normalising the name with hashing the unicode character? Uchar has a `hash` function which associates a non negative number with the character [here](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Uchar.html).

```
val hash : t -> int

hash u associates a non-negative integer to u.
```

**Comment by CraigFe** [comment]
Nice idea!

 As far as I understand, this still has the collision issue (although they are probably much less likely):

- `test-🔥`
- `test-11939`

However, https://github.com/mirage/alcotest/issues/175 means that these collisions will be caught during test registration.

We could also use `Printf.sprintf "U+%04x" (Uchar.to_int c)` to escape our currently unsupported characters. I think this (_a_) is a bit more standard for Unicode escapes and (_b_) avoids all collisions of differing OCaml strings (since we'd also be escaping the `+` char).
