### ISSUE TITLE
Unbound value Alcotest_lwt.run

### ISSUE THREAD

**Issue by shawn-mcginty** [mirage/alcotest#179]
Trying to follow the example for running tests w/ lwt, fails to compile with `Error: Unbound value Alcotest_lwt.run`

Am I missing something? Or is the documentation out of date?

**Comment by CraigFe** [comment]
I suspect that the documentation is actually _too_ in-date :wink: 

The examples in the `master` branch will fail to compile with the version of Alcotest that is released on opam (which I suspect is what you are using). `Alcotest_lwt.run` was added recently in [this PR](https://github.com/mirage/alcotest/pull/167). You can take a look at the Lwt example prior to this PR to see how it used to be done (e.g. https://github.com/mirage/alcotest/pull/165).

You could also pin Alcotest to master and use the unreleased API, but be warned that it's likely to change before being released (e.g. https://github.com/mirage/alcotest/pull/167#issuecomment-518565934).
