### ISSUE TITLE
Remove dependency on `tput`

### ISSUE THREAD

**Issue by CraigFe** [mirage/alcotest#183]
The `ocurrent` tests are failing becayse of a dependency on `tput` to determine the width of the TTY. This could be avoided by switching to a TIOCGWINSZ ioctl [as it is being done in Notty](https://github.com/pqwy/notty/blob/master/src-unix/native/winsize.c), or the terminal interactions could all be handled by adding a dependency to Notty directly.

**Comment by emillon** [comment]
There's also https://github.com/cryptosense/terminal_size which exposes just this ioctl if you don't want to add a dependency to notty.
