### ISSUE TITLE
Executable version is set from alcotest version

### ISSUE THREAD

**Issue by emillon** [mirage/alcotest#184]
Hi,

A test executable that uses alcotest comes with some command-line options, including `--help` that is provided by `cmdliner`.

The help message displays a version number, but it's alcotest's version number - not the current project, which I found surprising:

```
% cat dune
(test
 (name t)
 (libraries alcotest))

% cat t.ml
let () = Alcotest.run "test" []

% dune exec ./t.exe -- --help
(...)
T.exe 0.8.5                                                           T.EXE(1)
(END)
```

I suggest leaving out the `~version` argument here:

https://github.com/mirage/alcotest/blob/d388020b68e25559b779c19065d8c3e321a10a63/src/cli.ml#L181

What do you think?

**Comment by CraigFe** [comment]
This seems sensible to me; I don't think the version number is particularly meaningful anyway.
