### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by CraigFe** [mirage/alcotest#198]
It's been a long time since the last release (0.8.5 on 17 Jan), and the API has since been broken (in particular with `Alcotest_lwt` and `Alcotest_async` test cases now being run fully within their respective concurrency monads). 

Perhaps it's time for a 0.9.0 release? The following things should happen first:

- [ ] update the changelog
- [ ] cleanup any low-hanging fruit amongst the long-standing issues:
  - [x] ~~#72~~ (no longer selected for fixing on this release) 
  - [ ] #91 
  - [ ] #120 
  - [x] #121 
  - [ ] #151
- [ ] restore compatibility with unicode test names (#171)

Future feature improvements like #177 can probably wait for a future release, although it would be cool to squeeze them if if we can.

**Comment by avsm** [comment]
Sounds good -- I would bump the major version to 1.0 though, to reflect the breaking API change.

**Comment by CraigFe** [comment]
Release PR opened at https://github.com/ocaml/opam-repository/pull/15669. I'm still working through rev-deps at the moment.
