### ISSUE TITLE
Output to predictable location?

### ISSUE THREAD

**Issue by mjambon** [mirage/alcotest#201]
I wonder why the test logs, even with the `-o` option, go to a subfolder with a uuid-like name such as `_build/_tests/7F4CB0F7-69A1-434F-BA6A-F4162C1E04C9`. How is it useful? How to disable or override this?

**Comment by mjambon** [comment]
Having to write a script to locate the uuid folder and rename it is pretty annoying. Unless I'm missing something, I'd like to suggest adding a command-line option for setting the run ID.

I may send a PR tomorrow. Please just let me know if for some reason I shouldn't do this.

**Comment by hannesm** [comment]
the history about the output directory is #137 which introduced the behaviour and #155 (afaict unreleased, but merged into master) that creates a symlink `latest` pointing to the most recent testrun output. in my opinion, alcotest should not create fresh directories, if you want to preserve a testrun output, you're better off to copy the subdirectory elsewhere.

**Comment by mjambon** [comment]
@hannesm the symlink to `latest` as implemented by #155 will work fine for my needs as well. Thank you!
