### ISSUE TITLE
check with list of tuple (int*float)

### ISSUE THREAD

**Issue by Yaya0312** [mirage/alcotest#208]
Hello,

I wish to test the sum of two list of tuple but I have an error.
My IDE say me 

```
This expression has type 'a * 'b
       but an expression was expected of type
         'c Alcotest.testable =
```

My code test

`Alcotest.check (Alcotest.list (int,float))  "sum"
`

I understand the answer of my ide but i have not idea to resolve it.

Thanks

**Comment by CraigFe** [comment]
You need to use the `Alcotest.pair` combinator to combine the `int` and `float` testables before using `Alcotest.list`:

```ocaml
Alcotest.check Alcotest.(list (pair int float))) "sum"
```

However, this isn't quite right since `float` requires an explicit tolerance for equality, e.g.

```ocaml
Alcotest.check Alcotest.(list (pair int (float 0.0001)))) "sum"
```
Hope that solves your problem :slightly_smiling_face:
