### ISSUE TITLE
Testin the async lwt failure from the readme crashes the test instead of printing the failed output

### ISSUE THREAD

**Issue by tcoopman** [mirage/alcotest#211]
I'm trying this example from the readme, but instead of getting the output as shown in the readme, the tests just crash

```ocaml
let free () = print_endline "freeing all resources"; Lwt.return ()

let test_lwt switch () =
  Lwt_switch.add_hook (Some switch) free;
  Lwt.async (fun () -> failwith "All is broken");
  Lwt_unix.sleep 10.

let () =
  Lwt_main.run @@ Alcotest_lwt.run "foo" [
    "all", [
      Alcotest_lwt.test_case "one" `Quick test_lwt
    ]
  ]
```

output from the tests:

```
EventStormerTest alias tests/runtest (exit 2)
(cd /home/thomas/Workspace/ocaml/event-stormer/_esy/default/store/b/event_stormer-2553d4c6/default/tests && ./EventStormerTest.exe)
Testing DB Tests.
This run has ID `DF3F4B8E-A6F2-46A0-9525-E1C68B7537DD`.
 ...                all          0   one.
 ```

**Comment by CraigFe** [comment]
Thanks; I've reproduced this and am working on a fix.

**Comment by CraigFe** [comment]
On second pass, I'm not sure I _can_ reproduce this consistently. It's either a failure to flush std.out or some Lwt version-specific behaviour. I added this example as a test-case in https://github.com/mirage/alcotest/pull/212, and the CI gives the expected output of:
```
Testing foo.
This run has ID `<uuid>`.
 ...                all          0   one.freeing all resources
Fatal error: exception Failure("All is broken")
```

What dependency versions are you using?

**Comment by tcoopman** [comment]
I was trying both the latest opam version and latest master.
I've also seen it happen when I added the async failure somewhere halfway
in the lwt tests from the repo and the same thing happened

I'm not at a computer at the moment, I'll try again later

**Comment by CraigFe** [comment]
> I'm not at a computer at the moment, I'll try again later

Thanks :slightly_smiling_face: 

> I was trying both the latest opam version and latest master.

I'm thinking particularly about which versions of `Alcotest_lwt`'s dependencies you have installed in your switch. (`dune`, `lwt`, `logs`)

**Comment by tcoopman** [comment]
I'm using [esy](https://esy.sh/).

This is some output:

* dune: @opam/dune@opam:2.2.0@9f6b1c70
* logs:  opam/logs@opam:0.7.0@1d03143e
* lwt: @opam/lwt@opam:5.1.1@6f0a0b20
* alcotest-lwt: @opam/alcotest-lwt@github:mirage/alcotest:alcotest-lwt.opam#372065b3be9fcafc4dd223819a0a06b7a798252d@d41d8cd9
* ocaml: ocaml@4.8.1000@d41d8cd9

full alcotest-lwt deps: 
```
      "dependencies": [
        "ocaml@4.8.1000@d41d8cd9", "@opam/lwt@opam:5.1.1@6f0a0b20",
        "@opam/logs@opam:0.7.0@1d03143e", "@opam/dune@opam:2.2.0@9f6b1c70",
        "@opam/alcotest@github:mirage/alcotest:alcotest.opam#372065b3be9fcafc4dd223819a0a06b7a798252d@d41d8cd9",
        "@esy-ocaml/substs@0.0.1@d41d8cd9"
      ],
      "devDependencies": [
        "ocaml@4.8.1000@d41d8cd9", "@opam/lwt@opam:5.1.1@6f0a0b20",
        "@opam/logs@opam:0.7.0@1d03143e", "@opam/dune@opam:2.2.0@9f6b1c70",
        "@opam/alcotest@github:mirage/alcotest:alcotest.opam#372065b3be9fcafc4dd223819a0a06b7a798252d@d41d8cd9"
      ]
```

Do you have enough info with that?

**Comment by tcoopman** [comment]
Some more info. I noticed that you used `~verbose:true`, when using that I get the same output, but the test still finishes after that failure.

When I change the code from here: https://github.com/mirage/alcotest/blob/master/examples/lwt/test.ml
To include the failure (see below: `test_case "Foo" `Quick test_lwt;`) then the test outputs:

```
This run has ID `6B652895-EF41-4D67-AE48-57212731D6C7`.
[OK]                basic               0   Plain.
[OK]                basic               1   Lwt.
 ...                basic               2   Foo.freeing all resources
ASSERT same string
ASSERT same string
Fatal error: exception Failure("All is broken")
```

```ocaml
(* Run it *)
let () =
  let open Alcotest_lwt in
  Lwt_main.run
  @@ run ~verbose:true "LwtUtils"
       [
         ( "basic",
           [
             test_case_sync "Plain" `Quick test_lowercase;
             test_case "Lwt" `Quick test_lowercase_lwt;
             test_case "Foo" `Quick test_lwt;
           ] );
         ( "exceptions",
           [
             test_case_sync "Plain" `Quick test_exn;
             test_case "Lwt toplevel" `Quick test_exn_lwt_toplevel;
             test_case "Lwt internal" `Quick test_exn_lwt_internal;
           ] );
         ( "switches",
           [
             test_case "Allocate resource" `Quick test_switch_alloc;
             test_case "Check resource deallocated" `Quick test_switch_dealloc;
           ] );
       ]
```

**Comment by talex5** [comment]
I don't think this has anything to do with async exceptions. Even:

```ocaml
let test_lwt _switch () =
  Lwt.fail_with "should fail"
```

doesn't work. It looks like Alcotest just doesn't catch exceptions from Lwt tests and instead crashes out on the first failing test, but without showing any error message for some reason.

**Comment by talex5** [comment]
@CraigFe : It's suspicious that the monad doesn't have a catch operation. I tried adding one here, which seems to help: https://github.com/CraigFe/alcotest/pull/1

**Comment by CraigFe** [comment]
Indeed, thanks both. I've strengthened the existing test and added a new one to cover the `Lwt.fail_with` case, both of which are now handled properly by @talex5's `catch` inclusion.

@tcoopman, can you try pinning the [`CraigFe/failing-async-case`](https://github.com/CraigFe/alcotest/tree/failing-async-case) branch and seeing if that fixes your issue?

```
"resolutions": {
  "@opam/alcotest": "CraigFe/alcotest:alcotest.opam#failing-async-case",  
  "@opam/alcotest-lwt": "CraigFe/alcotest:alcotest_lwt.opam#failing-async-case",
}
```

**Comment by tcoopman** [comment]
That seems to fix the issue, thanks!
