### ISSUE TITLE
Request for a bugfix release with #222 (Lwt/Async fix for accepting a cmdliner term)

### ISSUE THREAD

**Issue by hcarty** [mirage/alcotest#224]
I ran into the issue fixed by #222 while porting some code to Alcotest 1.x.  I have pinned for now, but it would be useful to have a proper point release on opam if that's possible.

Thank you @CraigFe for making the fix!

**Comment by CraigFe** [comment]
Thanks :slightly_smiling_face:

I'm hoping to get https://github.com/mirage/alcotest/pull/228 merged ASAP, then make a patch release with those two changes fairly soon.

**Comment by CraigFe** [comment]
Now released: https://github.com/ocaml/opam-repository/pull/16137#event-3196593849.

Sorry for the delay!

**Comment by hcarty** [comment]
Thank you!
