### ISSUE TITLE
Test suite fails if there is a path separator in user-supplied strings.

### ISSUE THREAD

**Issue by mefyl** [mirage/alcotest#240]
It looks like Alcotest tries to use the test name verbatim to create the output file : 
```
Fatal error: exception Unix.Unix_error(Unix.ENOENT, "open", "/home/mefyl/dev/routine/mellifera/_build/default/tests/_build/_tests/8520A9D5-E675-42A0-9B41-883792EA0F62//some/hardcoded/path.000.output")
```

Which fails since parent directories (`some/hardcoded`) do not exist. Note that incidentally a leading slash works.

I'm keen on submitting a patch if the fix is agreed on. Do we want to escape the test names ?

**Comment by CraigFe** [comment]
What version of Alcotest are you on? This should have been "fixed" by https://github.com/mirage/alcotest/pull/161, which forbids path separators in test names and was released in 1.0.0.

A better solution is currently tracked by https://github.com/mirage/alcotest/issues/171, which does indeed suggest escaping our currently-unsupported characters.

**Comment by mefyl** [comment]
I'm using 1.1.0.

Actually, the separators were in the intermediate test names, not the test-case name. This triggers it:

```
open Alcotest

let () =
  run "Alcotest"
    [ ("/some/path", [ test_case "whatever" `Quick (fun () -> ()) ]) ]
```

yields

```
Testing Alcotest.
This run has ID `5F485A6C-B1F4-43E4-A060-F4E5177A78E9`.
 ...                /some/path          0   whatever.test.exe: internal error, uncaught exception:
          Unix.Unix_error(Unix.ENOENT, "open", "/tmp/alcotest/_build/_tests/5F485A6C-B1F4-43E4-A060-F4E5177A78E9//some/path.000.output")
          
```

**Comment by mefyl** [comment]
Well actually we are both talking about exactly the same thing, and I think I tracked the problem down to this :

```
utop #  let pattern = "^[a-zA-Z0-9_- ]+$" in
  let re = Re.(compile @@ Pcre.re pattern) in
  Re.execp re "some/name";;
- : bool = true
```

Which looks, at first glance, worrying to say the least, but I'm sure we're just missing the perfectly valid reason why this returns true.

**Comment by mefyl** [comment]
Ah. I missed that there's a space at the end of that pattern so it accepts everything from `'_'` to `' '`.

**Comment by emillon** [comment]
This still fails with alcotest 1.1.0:

> Unix.Unix_error(Unix.ENOENT, "symlink", ....)

That happened as I tried `Alcotest.run __FILE__ []` (which wasn't a great idea because of this)

**Comment by CraigFe** [comment]
This change hasn't been released yet, so that seems expected.

**Comment by emillon** [comment]
That fails on master as well, I think it's because the test names are normalized, but not the test suite name itself.

**Comment by CraigFe** [comment]
That makes sense, thanks.

We should be more systematic with the normalisation. Reopening this isssue to track that.
