### ISSUE TITLE
Expected and actual output do not stand enough in the output

### ISSUE THREAD

**Issue by christophe-riolo** [mirage/alcotest#252]
Hello, I am new to Alcotest and I have been perplexed when confronted with this output:
```
ASSERT Returns error
[failure] Error Returns error: expecting
Connect Error: connection error., got
Connect Error: connection error.
```
It took me way longer than I would like to admit to realise that the last dot was part of the punctuation of the sentence and I was wondering why `Connect Error: connection error.` was different from `Connect Error: connection error.`.
I think it would be clearer to separate more clearly the outputs, for instance:
```
ASSERT Returns error
[failure] Error Returns error
Expected:
Connect Error: connection error.
Actual:
Connect Error: connection error
```

**Comment by CraigFe** [comment]
Thanks for the suggestion!

We actually have an open PR that makes an almost identical change (https://github.com/mirage/alcotest/pull/246) and a WIP one that takes this a step further by highlighting the component of the output that is different (https://github.com/mirage/alcotest/pull/247). I hope those will solve your issue.
