### ISSUE TITLE
Provide an Alcotest.triple combinator

### ISSUE THREAD

**Issue by sheepduke** [mirage/alcotest#288]
Folks,

I knew that we can use `pair` function to test stuff like `(bool * bool)`, but how can I test `(bool * bool * bool)`?

**Comment by CraigFe** [comment]
Alcotest doesn't yet provide a `triple` combinator, but it's possible to build one oneself w/ the same approach as the [`pair` combinator](https://github.com/mirage/alcotest/blob/master/src/alcotest-engine/test.ml#L95-L97). Something like:


```ocaml
let triple a b c =
  let eq (a1, b1, c1) (a2, b2, c2) =
       Alcotest.equal a a1 a2
    && Alcotest.equal b b1 b2
    && Alcotest.equal c c1 c2
  in
  let pp pp_a pp_b pp_c =
    Fmt.(parens (
         using (fun (x, _, _) -> x) (box pp_a)
      ++ comma
      ++ using (fun (_, x, _) -> x) (box pp_b)
      ++ comma
      ++ using (fun (_, _, x) -> x) (box pp_c)
    ))
  in
  Alcotest.testable pp eq
```

Contributions welcome :-)

**Comment by sheepduke** [comment]
Oh that works!

So I created a PR for it:
#289
