### ISSUE TITLE
Test failures not printing expected/actual values

### ISSUE THREAD

**Issue by Zoetermeer** [mirage/alcotest#35]
When I run simple assertions on built-in checkers such as `int`, I see output that tells me a failure occurred -- but nothing about the values involved in the failure.  It looks to me like the implementation of `check` should be doing this, but it's not on version 0.4.2 (perhaps it has been fixed since then?).

Here's sample output:

![screen shot 2015-10-29 at 8 44 44 am](https://cloud.githubusercontent.com/assets/145886/10820132/bd5e4660-7e19-11e5-837b-ee825b20fc36.png)

It seems to me that `check` is throwing the exception, but somehow the message string is empty:

![screen shot 2015-10-29 at 8 51 06 am](https://cloud.githubusercontent.com/assets/145886/10820281/5fa47516-7e1a-11e5-831d-4a2c8f4c5632.png)

**Comment by samoht** [comment]
The current version (0.4.6) works better:

```
# Alcotest.(check int) "it works" 1 2;;
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
ASSERT it works
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Exception: Failure "Error it works: expecting 1, got 2.".
```
