### ISSUE TITLE
What is the number next to the test name when you run the tests?

### ISSUE THREAD

**Issue by mimoo** [mirage/alcotest#367]
![image](https://user-images.githubusercontent.com/1316043/203218608-5b52c67e-7795-4101-ac6e-857330ee1163.png)

^ in this example `string-case` has the number 1, and others have the number 0, wondering what this means :o

**Comment by MisterDA** [comment]
In this example, `Utils` is the name of the tested library, `string-case`, `string-concat`, `list-concat` are the names of the test suites (lists of test cases), and `Lower case` is the test case at index `0` of the first test suite, and `Capitalization` is the test case at index `1` of the first test suite.

**Comment by mimoo** [comment]
oh I see! That makes sense thanks :)
