### ISSUE TITLE
Errors from Lwt.async not shown

### ISSUE THREAD

**Issue by talex5** [mirage/alcotest#45]
The default async exception handler prints to stderr and exits. Since alcotest redirects stderr, the user doesn't see anything except that the tests stop with `...` displayed.

As a workaround, I use this in my tests:

```
let fd_stderr = Unix.descr_of_out_channel stderr
let real_stderr = Unix.dup fd_stderr
let () =
  let old_hook = !Lwt.async_exception_hook in
  Lwt.async_exception_hook := (fun ex ->
    Unix.dup2 real_stderr fd_stderr;
    Printf.eprintf "\nasync_exception_hook:\n%!";
    old_hook ex
  )
```

I'm not sure what the correct fix is, but the current situation doesn't seem ideal.

**Comment by talex5** [comment]
Ran into this again today (but forgot about this issue and came up with another solution). Maybe we should have an `Alcotest_lwt` package which does the necessary wrapping? I'm currently wrapping each test with:

```
let run_lwt fn () =
  let async_ex, async_waker = Lwt.wait () in
  let handle_exn ex =
    Logs.debug (fun f -> f "Uncaught async exception: %a" Fmt.exn ex);
    if Lwt.state async_ex = Lwt.Sleep then
      Lwt.wakeup_exn async_waker ex
  in
  Lwt.async_exception_hook := handle_exn;
  Lwt_main.run (Lwt_switch.with_switch (fun sw -> Lwt.pick [fn sw; async_ex]))
```

**Comment by samoht** [comment]
Good idea for the `Alcotest_lwt` package.
