### ISSUE TITLE
Terminal mangling issues?

### ISSUE THREAD

**Issue by ihodes** [mirage/alcotest#53]
Trying to get an extremely simple test case working (pared it down for this issue) but am running into issues:

```ocaml
let strip_chr () =
  Alcotest.(check (list string)) "removed chrs when needed"
    ["1"; "2"; "2"; "MT"; "X"; "JH584295.1"; "GL456382.1"]
    ["1"; "2"; "2"; "MT"; "X"; "JH584295.1"; "GL456382.1"]

let utility_tests = [
  "Remove chr from chromosomes if necessary", `Quick, strip_chr;
]

let () =
  Alcotest.run "Test FASTA sorting" [
    "utils", utility_tests;
  ]
```

Running this test gives me:

![screen shot 2016-04-21 at 2 05 15 pm](https://cloud.githubusercontent.com/assets/167803/14719428/23e8c2d6-07ca-11e6-95ea-b480a9c9b043.png)

You can see the text is not quite right… it gets more confusing when there is a failure, e.g.:

```ocaml
let strip_chr () =
  Alcotest.(check (list string)) "removed chrs when needed"
    ["2"; "2"; "MT"; "X"; "JH584295.1"; "GL456382.1"]
    ["1"; "2"; "2"; "MT"; "X"; "JH584295.1"; "GL456382.1"]
```

![screen shot 2016-04-21 at 2 06 38 pm](https://cloud.githubusercontent.com/assets/167803/14719456/49ed8aca-07ca-11e6-9bba-82fca6d2325b.png)

```
opam info alcotest
             package: alcotest
             version: 0.4.8
          repository: default
        upstream-url: https://github.com/mirage/alcotest/archive/0.4.8.tar.gz
       upstream-kind: http
   upstream-checksum: e293617063cb379442d5f5b12a373b04
            homepage: https://github.com/mirage/alcotest/
         bug-reports: https://github.com/mirage/alcotest/issues/
            dev-repo: https://github.com/mirage/alcotest.git
              author: Thomas Gazagnaire
             license: ISC
             depends: ocamlfind & ocamlbuild & oasis & astring & result & cmdliner
   installed-version: 0.4.8 [4.02.3]
  available-versions: 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.4.8
         description: Alcotest is a lightweight and colourful test framework.
```

**Comment by Drup** [comment]
I have the same issue.

**Comment by samoht** [comment]
That's weird. Which shell are you using (not sure where to start to debug that, I never noticed that issue).

**Comment by Drup** [comment]
I'm using zsh.

**Comment by samoht** [comment]
I managed to repro, I'll fix that shortly.

**Comment by ihodes** [comment]
I am using bash, for what it's worth. Thanks for looking into it!

**Comment by rizo** [comment]
I am still experiencing this issue, both with `0.4.11` and latest master (`e2bd290d`). The list testables are concatenated without separators.

Here is the basic example from utop:

![screen shot 2016-05-31 at 13 41 41](https://cloud.githubusercontent.com/assets/308413/15674613/a2f8d5f4-2735-11e6-9212-17ceb497652b.png)

Package details:

![screen shot 2016-05-31 at 13 42 03](https://cloud.githubusercontent.com/assets/308413/15674648/d492ca84-2735-11e6-9459-fb7d1408253d.png)

**Comment by talex5** [comment]
Maybe Alcotest could print lists with `Fmt.Dump.list`?
