### ISSUE TITLE
Misalignment of lines showing failed tests

### ISSUE THREAD

**Issue by darioteixeira** [mirage/alcotest#60]
With Alcotest 0.4.8, lines were always neatly aligned, regardless of whether the test had succeeded for failed. This is no longer the case with versions 0.4.9 and 0.4.10: lines containing failed tests are misaligned.

**Comment by samoht** [comment]
Thanks for the report, I'll make a new release with a fix very soon.

**Comment by samoht** [comment]
See https://github.com/ocaml/opam-repository/pull/6509

**Comment by darioteixeira** [comment]
Wow, that was fast. Thanks!
