### ISSUE TITLE
test name output longer than a terminal line looks strange

### ISSUE THREAD

**Issue by hannesm** [mirage/alcotest#72]
```
[OK]                RepositoryReleases               2   not authorised.
[OK]                RepositoryReleases               3   bad release.
 ...                RepositoryReleases               4   name mismatch (releases and authorisation
[OK]                RepositoryReleases               4   name mismatch (releases and authorisation
).
```

the 3rd line looks well formatted (cut before the line wrapping), whereas the 4th line is printed as a new line, and includes a line wrapping (for `).`).

**Comment by CraigFe** [comment]
Have reproduced this on `master`. Three years later, what do you suggest we do to fix the formatting in this case? Perhaps not print the `pending` line if it's wider than the terminal?

**Comment by CraigFe** [comment]
On closer inspection, as a result of https://github.com/mirage/alcotest/pull/189 it's no longer simple to fix this issue: we no longer track the width of the terminal.

We could do this without a dependency on `tput` by using the `TIOCGWINSZ` ioctl, as in https://github.com/cryptosense/terminal_size.
