### ISSUE TITLE
Is there any way to check None or Some?

### ISSUE THREAD

**Issue by grigoriytretyakov** [mirage/alcotest#73]
For example, I write a function, which return the last element of list.

```
let rec last = function
    | [] -> None
    | [elem] -> Some elem
    | hd :: tl -> last tl
```

And I want to write something like this:

```
Alcotest.(check (option None)) "Last from empty list" None (last [])
```

Can I make it using Alcotest?

**Comment by talex5** [comment]
You need `option elt_type` instead of `option None`. If you don't care about printing the Some case nicely, you can use `option reject`.
