### ISSUE TITLE
Add a more generic check_raises

### ISSUE THREAD

**Issue by samoht** [mirage/alcotest#88]
The current one uses a strict equality, but in some cases you really want to pattern match on the exception to decide whether the function raised something in the right family of errors.

**Comment by MathiasMalandain** [comment]
I would like to "up" this issue. Being able to match something like `Failure _` or `Sys_error _` in a test would be great, particularly as the string literal is not something to be matched on, even according to [the StdLib documentation](https://v2.ocaml.org/api/Stdlib.html#EXCEPTIONFailure).
