### ISSUE TITLE
same_string failure is hard to read/debug

### ISSUE THREAD

**Issue by zapashcanon** [mirage/alcotest#90]
Hi,

When dealing with strings starting/ending with spaces or new lines, the output is hard to read. E.g.

```
[failure] Error same string: expecting    blablabla

blablabla

    , got      blablabla

blablabla

    
.
```

It would be great to change the output to something like:

```
[failure] Error same string:
expecting:
---
    blablabla

blablabla

    
---
got:
---
      blablabla

blablabla

    
---
```

**Comment by samoht** [comment]
It should be fixed by https://github.com/mirage/alcotest/pull/86

**Comment by zapashcanon** [comment]
This fix the start of the string, but not the end, I'll submit a PR as it looks easy to fix.
